
FROM node:20-alpine

WORKDIR /app

COPY  package*.json ./

RUN npm install

COPY  . .

EXPOSE 5173

CMD [ "npm"," run","preview"  ]
# CMD [ "npm"," run","preview" ] in json in read add --host --port 5173














